on: [push, pull_request]

name: Run Tests

jobs:
  testing:
    name: Testing-${{ matrix.toolchain }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.70.0
          - stable
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal

      - name: Run cargo test
        working-directory: pycoingecko-rs
        run: cargo test --release --workspace

  testing-blas:
    name: Testing-with-BLAS-${{ matrix.toolchain }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.70.0
          - stable
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal

      - name: Install dependencies for BLAS
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libblas-dev liblapack-dev

      - name: Run cargo test
        working-directory: pycoingecko-rs
        run: cargo test
